### ISSUE TITLE
[BUG] code generate failed in cudnn, RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by haozhou-wong** [Bruce-Lee-LY/cuda_hook#14]
I am trying to execute code_generate.sh in bash but failed, and the log of console is shown as below

```
cuda total func num: 485
cuda valid func num: 378
nvml total func num: 251
nvml valid func num: 251
cudart total func num: 357
cudart valid func num: 297
Traceback (most recent call last):
  File "/home/haozhou/work_wsl/cuda_hook/tools/code_generate/code_generate.py", line 162, in <module>
    main()
  File "/home/haozhou/work_wsl/cuda_hook/tools/code_generate/code_generate.py", line 156, in main
    code_gen.parsę_header()
  File "/home/haozhou/work_wsl/cuda_hook/tools/code_generate/code_generate.py", line 49, in parsę_header
    self.header = CppHeader(self.file)
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 2390, in __init__
    self.finalize()
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1576, in finalize
    self.finalize_vars()
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1307, in finalize_vars
    self.resolve_type( var['type'], var )
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1288, in resolve_type
    self.resolve_type( self.typedefs[alias], result )
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1288, in resolve_type
    self.resolve_type( self.typedefs[alias], result )
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1288, in resolve_type
    self.resolve_type( self.typedefs[alias], result )
  [Previous line repeated 988 more times]
  File "/home/haozhou/.local/lib/python3.10/site-packages/CppHeaderParser/CppHeaderParser.py", line 1260, in resolve_type
    result[ 'constant' ] += s.split().count('const')
RecursionError: maximum recursion depth exceeded in comparison
```

I also tried edit maximum recursion depth by sys.setrecursionlimit(10000) in code_generate.py, but it didn't work.

**Comment by haozhou-wong** [comment]
sorry, I miss the cppheaderparser version, using robotpy-cppheaderparser can be solved
